In [1]:
import numpy as np

## Transforming a list to numpy array

In [2]:
mylist = [1,2,3]
myarr = np.array(mylist)
myarr

array([1, 2, 3])

In [3]:
type(myarr)

numpy.ndarray

In [4]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
matrix = np.array(my_matrix)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Functions

In [5]:
# numpy.arange - numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None): Return evenly spaced values within a given interval.

np.arange(0,100,20)

array([ 0, 20, 40, 60, 80])

In [6]:
print(np.zeros(5))
print()
print(np.zeros((3,5)))

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
print(np.ones(4))
print()
print(np.ones((4,4)))

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
# numpy.linspace -numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0): 
    # Return evenly spaced numbers over a specified interval.
    
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.random.rand(3,2)

array([[0.54924592, 0.42901869],
       [0.56698324, 0.04834067],
       [0.49931424, 0.86556915]])

In [11]:
print(np.random.randn(2,3))
print()
np.random.randn(10)

[[ 0.68548122 -0.32942805 -1.97170184]
 [-1.61817752  1.13444565  0.99927633]]



array([ 0.08742957,  0.35752185,  0.17759855, -0.01069081,  0.16645133,
        0.72591581,  2.30876864,  1.80301701, -1.32110901,  0.0875066 ])

In [12]:
np.random.randint(0,101, (4,6))

array([[38, 55, 15, 82, 84, 79],
       [60, 62, 97, 84, 80,  7],
       [73, 36, 99, 67, 99,  5],
       [96, 16, 56, 64, 20, 21]])

In [13]:
np.random.seed(42)
np.random.randint(4)

2

In [14]:
ranarr = np.random.randint(0,101,10)
ranarr

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [15]:
ranarr.max()

92

In [16]:
ranarr.min()

14

In [17]:
# Returns the indices of the maximum values along an axis.
ranarr.argmax()

1

In [18]:
# Returns the indices of the minimum values along an axis.
ranarr.argmin()

2

In [19]:
ranarr.shape

(10,)

In [20]:
arr = ranarr.reshape(2,5)
arr

array([[51, 92, 14, 71, 60],
       [20, 82, 86, 74, 74]])

## Indexing and Selection

In [21]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr[8]

8

In [23]:
arr[1:5]

array([1, 2, 3, 4])

In [24]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [25]:
slice_of_arr = arr[:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [26]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [27]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [28]:
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [29]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [30]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr_2d.shape

(3, 3)

In [32]:
print(arr_2d[0])
print(arr_2d[2])

[ 5 10 15]
[35 40 45]


In [33]:
print(arr_2d[1,1])
print()
print(arr_2d[0,2])
print()
print(arr_2d[2,2])

25

15

45


In [34]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [35]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [37]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

## Numpy Operations

In [39]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [42]:
arr + arr 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [43]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [44]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [46]:
arr.sum()

55

In [47]:
arr.mean()

5.5

In [48]:
arr.var()

8.25

In [49]:
arr.std()

2.8722813232690143

In [50]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr2d.sum()

300

In [52]:
# Perform the operations across the rows
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [53]:
# Perform the operations across the columns
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])