In [1]:
import numpy as np
from numpy import array

In [2]:
#Transpose
A = array([
    [1,2],
    [3,4],
    [5,6]])
C = A.T
C

array([[1, 3, 5],
       [2, 4, 6]])

In [3]:
# Inverse
D = array([[1,2], [3,4]])
B = np.linalg.inv(D) 
B

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [4]:
I = A.dot(B)
I

array([[ 1.00000000e+00,  1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00],
       [-1.00000000e+00,  2.00000000e+00]])

In [5]:
inverse = np.around(I)
inverse

array([[ 1.,  0.],
       [ 0.,  1.],
       [-1.,  2.]])

In [6]:
M = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
m_trace = np.trace(M)
m_trace

15

In [7]:
from numpy.linalg import det
#D = np.linalg.det(M)
D = det(M)
D

6.66133814775094e-16

## Types of matrices

1. Square matrix - Number of rows = no of columns.

2. Symmetric matrix- it's a square matrix that is equal to its transpose.

3. Triangular matrix- A square matrix is said to be:
     1. lower triangular if all the elements above its main diagonal are zero;
     2. upper triangular if all the elements below its main diagonal are zero.
     
4. Diagonal matrix- it's one where values outside of the main diagonal have a zero value. 

5. Identity matrix- it's a square matrix where all the scalar values along the main diagonal are 1, while other values are 0.

6. Orthogonal matrix- A matrix Q is orthogonal if its transpose is equal to its inverse

In [8]:
# Symmetric matrix
N = array([
    [1,2,3,4],
    [2,1,2,3],
    [3,2,1,2],
    [4,3,2,1]
])
R = N.T
R

array([[1, 2, 3, 4],
       [2, 1, 2, 3],
       [3, 2, 1, 2],
       [4, 3, 2, 1]])

In [9]:
#Diagonal matrix
d = np.diag(N)
d

array([1, 1, 1, 1])

In [10]:
#Identity matrix
E = np.diag(d)
E

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [11]:
v = array([4,0,9,2])
np.dot(E,v)

array([4, 0, 9, 2])

In [12]:
np.dot(v,E)

array([4, 0, 9, 2])

In [13]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
#Orthogonal martrix - np.dot(Q, Q.T) = Identity matrix
Q = array([[1,0],[0,-1]])
Q

array([[ 1,  0],
       [ 0, -1]])

In [15]:
q = Q.T
q

array([[ 1,  0],
       [ 0, -1]])

In [16]:
s = np.dot(Q, q)
s

array([[1, 0],
       [0, 1]])