In [1]:
import numpy as np
from numpy import array

In [4]:
#Transpose
A = array([
    [1,2],
    [3,4],
    [5,6]])
C = A.T
C

array([[1, 3, 5],
       [2, 4, 6]])

In [11]:
# Inverse
D = array([[1,2], [3,4]])
B = np.linalg.inv(D) 
B

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [12]:
I = A.dot(B)
I

array([[ 1.00000000e+00,  1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00],
       [-1.00000000e+00,  2.00000000e+00]])

In [13]:
inverse = np.around(I)
inverse

array([[ 1.,  0.],
       [ 0.,  1.],
       [-1.,  2.]])

In [14]:
M = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
m_trace = np.trace(M)
m_trace

15