# What you learn in this course

In the following lessons you will learn:

* How to import NumPy
* How to create multidimensional NumPy ndarrays using various methods
* How to access and change elements in ndarrays
* How to use slicing to select or change subsets of  ndarray
* Understand the difference between a view and a copy of  ndarray
* How to use Boolean indexing and set operations to select or change subsets of an ndarray
* How to sort ndarrays
* How to perform element-wise operations on ndarrays
* Understand how NumPy uses broadcasting to perform operations on ndarrays of different sizes.






# NumPy 

NumPy stands for Numerical Python. It is an important package in python built on C programming, used for scientific computations on arrays and matrix (multidimensional) data structures.
It provides basis for a lot of other python packages.
It's incredibly fast, as it has bindings to C libraries. 

### Installation
Like any python library, numpy can be installed using:

**pip install numpy** (on command prompt)

**conda install numpy** (on anaconda terminal)

If you are installing it jupyter notebook start the code with !.

**!pip install numpy** 


# Advantages of NumPy

* It has high speed.

* It has multidimensional array data structures that can represent vectors and matrices.

* It has a large number of optimized built-in mathematical functions.


### Speed test

In [1]:
import time
import numpy as np

In [2]:
x = np.random.random(10000000)

In [3]:
#Case 1 (using core python)
start = time.time()
sum(x) / len(x)
print('Time used by core python :',time.time() - start)


Time used by core python : 1.1567537784576416


In [4]:
# Case 2 (using numpy)

start = time.time()
np.mean(x)
print('Time used by numpy: ',time.time() - start)

Time used by numpy:  0.019003868103027344


In [5]:
!pip install numpy

### Importing NumPy

Conventionally, numpy is imported and aliased as np as shown in the code below.



In [6]:
import numpy as np

# Numpy data structures

The main data structure of numpy is called numpy arrays.

Numpy arrays can essentially come in other structures namely: vectors and matrices.

Vectors are strictly 1-d arrays and matrices are 2-d (**Note**:a matrix can still have only one row or one column).




# Numpy arrays

Numpy Array refers to a list of elements of the **same type**. 

It is the main data structure of numpy. 

Unlike the traditional python list, numpy arrays are always of the same data type with flexibility for manipulation and mathematical operations. 

Arrays can be single or multidimensional. 

The next session demonstrates how arrays can be created with numpy.

### Array Creation.

Numpy array created in two main ways:
1. by using the np.array()
2. by using numpy built -in functions to create specific arrays.

#### One dimensional array using np.array() method

In [7]:
array_1 = np.array((2,4,6))

array_1


array([2, 4, 6])

In [8]:
type(array_1)

numpy.ndarray

#### Creating an array from an already existing  list

In [9]:

my_list = [1,2,3]
my_list

[1, 2, 3]

In [10]:
np.array(my_list)

array([1, 2, 3])

#### Creating a matrix from a list  of list

In [11]:
list_of_list = [[1,2,3],
                [4,5,6],
                [7,8,9]]
list_of_list


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
matrix_1=np.array(list_of_list)
matrix_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Functions

Numpy has a lot of  built-in methods to generate arrays 

### arange

The arange() method returns evenly spaced values within a given interval.

In [13]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
type(range(0,10))

range

In [15]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

### linspace
The linspace() method returns evenly spaced numbers over a specified interval.

In [18]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

In [19]:
np.linspace(0,25,5)


array([ 0.  ,  6.25, 12.5 , 18.75, 25.  ])

### zeros and ones

Generate arrays of zeros or ones

In [20]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.ones((3,3),dtype = 'int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## eye

The eye() function creates an identity matrix


In [24]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

## Random Sampling

Numpy has a lot of methods to create random number arrays

In [25]:
x = np.random.random((3,2))
print(x)

[[0.22542545 0.83206652]
 [0.98489021 0.6496852 ]
 [0.86731353 0.93591722]]


In [26]:
from numpy.random import random
random((3,3))

array([[0.43558114, 0.04280071, 0.2767667 ],
       [0.7898597 , 0.01788383, 0.50306893],
       [0.25235995, 0.06229532, 0.90801616]])



### rand
The rand method creates an array of the given shape and populate it with random samples from a uniform distribution.
Note that the values of a uniform distribution is between 0 and 1. 


In [27]:
np.random.rand(2)

array([0.22331929, 0.77694853])

In [28]:
np.random.rand(3,5)

array([[0.2787568 , 0.29201309, 0.01864593, 0.75366111, 0.25959267],
       [0.88613213, 0.15357618, 0.27931582, 0.74462192, 0.37938224],
       [0.70200579, 0.76521723, 0.24581918, 0.25230034, 0.39789995]])

### randn

The randn returns sample from the "standard normal" distribution.

In [29]:
np.random.randn(10)

array([-0.45146176, -1.86655497, -0.9816272 , -1.1999493 ,  0.42949509,
        1.45587512,  0.75829726, -1.23951554, -0.11192386, -0.64456316])

In [30]:
np.random.randn(5,5)

array([[ 0.73372182, -0.32622909, -0.46699972, -1.01886219,  0.42225828],
       [-0.25192499, -0.46174911, -0.33295484,  0.3915954 ,  1.31333559],
       [ 1.281378  ,  0.69341466,  2.09832635, -0.5457972 ,  1.81966081],
       [ 1.45740639,  0.65708468,  0.36442489,  1.52907829,  1.05117636],
       [-0.88089417, -0.32549247, -0.1655086 ,  0.70615502, -1.10308997]])

In [31]:
# Random normal with mean = 0 and standard deviation equal = 0.1,size = 100 by 100

x = np.random.normal(2,0.003,size = (100,100))
print(x)

[[1.99457515 2.00512704 2.00266989 ... 2.00127964 1.99484096 2.00161333]
 [1.99641199 1.99875951 2.0003467  ... 1.99839662 2.00031141 1.99808976]
 [2.00057853 1.9989538  2.00061585 ... 1.99793017 1.99782952 1.99732631]
 ...
 [2.00397867 1.99884424 2.00735417 ... 2.00436677 1.99996698 2.00082218]
 [2.0022316  1.993859   1.99834462 ... 1.9997962  2.00235533 1.99686227]
 [1.99766242 2.00322866 1.99988882 ... 2.00149269 1.99836618 1.99906783]]


In [32]:
print('mean',np.mean(x))
print('std',x.std())
print('max',x.max())
print('# positive',(x>0).sum())
print('# Negative',(x<0).sum())

mean 1.9999993935075224
std 0.0030058995348171903
max 2.0110195766551713
# positive 10000
# Negative 0


### randint
The randint method returns random integers.

In [33]:
np.random.randint(1,100)# returns a value  between 1 and 100

61

In [34]:
np.random.randint(1,100,10)# returns 10 value  between 1 and 100

array([87, 61,  9, 77, 88, 98, 37, 42, 31, 70])

In [35]:
np.random.randint(4,25,(3,2))

array([[11,  6],
       [19,  7],
       [11, 22]])

## Attributes and Methods of NumPy Array



In [36]:
# Creating two arrays for illustrations.

array_1 = np.arange(25)
array_2 = np.random.randint(1,50,20)

In [37]:
array_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
array_2

array([36, 27, 20,  5, 29, 49, 48, 43, 30, 31,  3, 43,  3, 16, 27, 14,  1,
       24, 30, 44])

## Shape

Shape is an attribute that arrays have (not a method):

In [39]:
# Vector
array_1.shape

(25,)

## Reshape

The reshape method returns an array containing the same data with a new shape.

In [40]:
array_1.shape

(25,)

In [41]:
np.reshape(array_1,(5,5)) # using reshape as a function 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
array_1.reshape(5,5)# using reshape as amethod

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
array_2 = np.random.randint(1,50,20)

In [44]:
array_2.shape

(20,)

In [45]:
arr=array_2.reshape(10,2)

In [46]:
arr.size

20

In [47]:
arr.shape

(10, 2)

In [48]:
array_1.reshape(5,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

max and min methods are used  for finding max or min values whiles argmax and argmin are used to find the index locations of the max and min values respectively.

In [49]:
array_2

array([36,  3, 22, 24, 33, 34, 12, 11, 27,  5, 27, 16, 20,  8, 10, 49, 14,
       26, 21, 20])

In [50]:
array_2.max()

49

In [51]:
array_2.argmax()

15

In [52]:
array_2.min()

3

In [53]:
array_2.argmin()

1

In [54]:
# mean
array_2.mean()

20.9

In [55]:
np.mean(array_2)

20.9

In [56]:
array_2.std()

11.304423912787419

In [57]:
array_2.var()

127.79000000000003

# size
The size method returns the size of the array

In [58]:
array_1.size

25

# ndim
This method returns the dimention of the an array



In [59]:
array_1.ndim

1

In [60]:
array_1.reshape(5,5).ndim

2

### dtype

The dtype method can be used to grab the data type of the object in the array.


In [61]:
type(array_1)

numpy.ndarray

In [62]:
array_1.dtype

dtype('int32')

### Specifying a dtype in array creation.

In [63]:
array_3 = np.array([3,4.5,6,9.9,7.2],dtype = np.int64)

In [64]:
array_3.dtype

dtype('int64')

In [65]:
array_3

array([3, 4, 6, 9, 7], dtype=int64)

Assignment: Create a guessing game that generates a random number between 1 to 6. The user will be given three trails to guess the right number. if the number is higher than the guessed number the game will indicate that the user should try a lower number and vice-versa. After three trials if the user fails the guess print the correct number.

In [81]:
import random

num = random.randint(0, 6)
attempt = 3 
msg = 'You Lost!'   

while attempt > 0:
    user_input = int(input('Enter Number: '))

    if user_input == num:
        msg = 'You Won!'
        break
    elif user_input > num:
        print('Try a Lower Number')
        attempt -= 1
        continue
    elif user_input < num:
        print('Try a Higher Number')
        attempt -= 1
        continue
    else:
        print(f'Try again! {attempt} attempt left.')
        attempt -= 1
        continue

print(msg)

Enter Number:  5


Try a Lower Number


Enter Number:  1


Try a Higher Number


Enter Number:  1


Try a Higher Number
You Lost!
